Repository YETDA/backend, pull requests merged in 2025-07, with the labels that each got.

#7 [ fix ] 6: 구매 카테고리 연관관계 오류 해결
  backend/src/main/java/com/funding/backend/domain/project/entity/Project.java
  backend/src/main/java/com/funding/backend/domain/purchaseCategory/entity/PurchaseCategory.java
Labels: fix

#11 [ feat ] : 10 docker 파일 추가
  backend/docker-compose.yml
Labels: feat

#12 [ feat ] 5 : s3 이미지 기능 구현
  backend/build.gradle.kts
  backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/funding/backend/domain/projectImage/entity/ProjectImage.java
  backend/src/main/java/com/funding/backend/domain/projectImage/repository/ProjectImageRepository.java
  backend/src/main/java/com/funding/backend/global/config/AwsS3Config.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
  backend/src/main/java/com/funding/backend/global/utils/CreateRandomNumber.java
  backend/src/main/java/com/funding/backend/global/utils/s3/ImageService.java
  backend/src/main/java/com/funding/backend/global/utils/s3/S3Uploader.java
Labels: feat

#14 [ feat ] 13 : 구매 옵션 생성, 수정 구현
  backend/src/main/java/com/funding/backend/domain/option/controller/OptionController.java
  backend/src/main/java/com/funding/backend/domain/option/dto/request/OptionRequestDto.java
  backend/src/main/java/com/funding/backend/domain/option/dto/response/OptionResponseDto.java
  backend/src/main/java/com/funding/backend/domain/option/repository/OptionRepository.java
  backend/src/main/java/com/funding/backend/domain/option/service/OptionService.java
  backend/src/main/java/com/funding/backend/domain/project/dto/request/PurchaseOptionDto.java
  backend/src/main/java/com/funding/backend/domain/project/dto/request/PurchaseProjectDetail.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/controller/OptionController.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/request/PurchaseOptionRequestDto.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/response/OptionResponseDto.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/entity/PurchaseOption.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/repository/PurchaseOptionRepository.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/service/PurchaseOptionService.java
Labels: feat

#22 [ feat] 17 : 공지사항 기능 구현
  backend/src/main/java/com/funding/backend/domain/notice/controller/NoticeController.java
  backend/src/main/java/com/funding/backend/domain/notice/dto/request/NoticeCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/notice/dto/request/NoticeRequestDto.java
  backend/src/main/java/com/funding/backend/domain/notice/dto/request/NoticeUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/notice/dto/response/NoticeReseponseDto.java
  backend/src/main/java/com/funding/backend/domain/notice/entity/Notice.java
  backend/src/main/java/com/funding/backend/domain/notice/repository/NoticeRepository.java
  backend/src/main/java/com/funding/backend/domain/notice/service/NoticeService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#30 [ feat ] 26 : 구매 옵션 기능 구현 crud, 구매 프로젝트 생성 방식 수정
  backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/funding/backend/domain/project/dto/request/ProjectCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/PurchaseProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/entity/Project.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseOptionRequestDto.java
  backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseProjectDetail.java
  backend/src/main/java/com/funding/backend/domain/purchase/dto/request/PurchaseUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/purchase/entity/Purchase.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/controller/OptionController.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/controller/PurchaseOptionController.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/request/PurchaseOptionCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/request/PurchaseOptionUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/response/OptionResponseDto.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/dto/response/PurchaseOptionResponseDto.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/entity/PurchaseOption.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/repository/PurchaseOptionRepository.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/service/PurchaseOptionService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
  backend/src/main/java/com/funding/backend/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/funding/backend/global/utils/ApiResponse.java
  backend/src/main/java/com/funding/backend/global/utils/s3/ImageService.java
  backend/src/main/java/com/funding/backend/global/utils/s3/S3Uploader.java
Labels: feat, fix

#33 [ Feat ] 28 : 좋아요 기능 구현
  backend/src/main/java/com/funding/backend/domain/like/controller/LikeController.java
  backend/src/main/java/com/funding/backend/domain/like/dto/request/LikeRequestDto.java
  backend/src/main/java/com/funding/backend/domain/like/dto/response/LikeResponseDto.java
  backend/src/main/java/com/funding/backend/domain/like/entity/Like.java
  backend/src/main/java/com/funding/backend/domain/like/repository/LikeRepository.java
  backend/src/main/java/com/funding/backend/domain/like/service/LikeService.java
Labels: feat

#45 [ feat ] 44 : 구매 옵션 기능 사용시 사용자 본인이 아니면 기능 사용 불가
  backend/src/main/java/com/funding/backend/domain/project/entity/Project.java
  backend/src/main/java/com/funding/backend/domain/purchase/entity/Purchase.java
  backend/src/main/java/com/funding/backend/domain/purchase/repository/PurchaseRepository.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/repository/PurchaseOptionRepository.java
  backend/src/main/java/com/funding/backend/domain/purchaseOption/service/PurchaseOptionService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
  backend/src/main/resources/application.yml
Labels: feat

#46 [ deploy ] 35 : 배포 과정 준비 (GIthub Action 수정, .env 적용)
  .github/workflows/deploy.yml
  backend/build.gradle.kts
  backend/src/main/java/com/funding/backend/BackendApplication.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-docker.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: deploy

#43 [ feat ] 42 : 창작물 프로젝트 생성시 유저 식별 기능 추가
  backend/src/main/java/com/funding/backend/domain/project/dto/request/ProjectCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#52 [ Feat ] 39 팔로우 기능 구현
  backend/src/main/java/com/funding/backend/domain/follow/controller/FollowController.java
  backend/src/main/java/com/funding/backend/domain/follow/dto/response/FollowCountResponse.java
  backend/src/main/java/com/funding/backend/domain/follow/dto/response/FollowResponseDto.java
  backend/src/main/java/com/funding/backend/domain/follow/entity/Follow.java
  backend/src/main/java/com/funding/backend/domain/follow/repository/FollowRepository.java
  backend/src/main/java/com/funding/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/funding/backend/domain/user/service/UserService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#57 [ merge ] 56 : dev 코드 배포 브랜치에 병합
  backend/src/main/java/com/funding/backend/domain/follow/controller/FollowController.java
  backend/src/main/java/com/funding/backend/domain/follow/dto/response/FollowCountResponse.java
  backend/src/main/java/com/funding/backend/domain/follow/dto/response/FollowResponseDto.java
  backend/src/main/java/com/funding/backend/domain/follow/entity/Follow.java
  backend/src/main/java/com/funding/backend/domain/follow/repository/FollowRepository.java
  backend/src/main/java/com/funding/backend/domain/follow/service/FollowService.java
  backend/src/main/java/com/funding/backend/domain/user/service/UserService.java
  backend/src/main/java/com/funding/backend/global/config/WebConfig.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: merge

#58 [ refact ] : 54 응답형식 통일 및 예외처리 통일
  backend/src/main/java/com/funding/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/funding/backend/security/jwt/TokenService.java
  backend/src/main/java/com/funding/backend/security/oauth/model/CustomOAuth2User.java
  backend/src/main/java/com/funding/backend/security/oauth/provider/GithubOAuthUserParser.java
  backend/src/main/java/com/funding/backend/security/oauth/provider/KakaoOAuthUserParser.java
Labels: refactor

#66 [ fix ] : 59 소셜로그인 수정
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
Labels: fix

#80 [ feat ] 76 : 검색 기능 구현
  backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/ProjectSearchResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#83 [ feat ] 65 : 본인이 결제 또는 후원한 프로젝트 조회 기능, 본인이 구매한 프로젝트 내역 조회 기능
  backend/src/main/java/com/funding/backend/domain/order/controller/OrderController.java
  backend/src/main/java/com/funding/backend/domain/order/controller/PurchaseOrderController.java
  backend/src/main/java/com/funding/backend/domain/order/dto/response/OrderResponseDto.java
  backend/src/main/java/com/funding/backend/domain/order/entity/Order.java
  backend/src/main/java/com/funding/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/funding/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/funding/backend/domain/order/service/PurchaseOrderService.java
  backend/src/main/java/com/funding/backend/domain/orderOption/dto/response/OrderOptionResponseDto.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
  backend/src/main/java/com/funding/backend/global/toss/controller/TossController.java
  backend/src/main/java/com/funding/backend/global/toss/dto/response/TossPaymentsResponseDto.java
  backend/src/main/java/com/funding/backend/global/toss/service/TossService.java
  backend/src/main/resources/application-local.yml
Labels: feat

#79 [ feat ] 8 : 후원(개발물) 프로젝트 CRUD 구현
  backend/src/main/java/com/funding/backend/domain/donation/controller/DonationController.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationProjectDetail.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/response/DonationProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java
  backend/src/main/java/com/funding/backend/domain/donation/repository/DonationRepository.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationProjectService.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/mainCategory/controller/MainCategoryController.java
  backend/src/main/java/com/funding/backend/domain/mainCategory/dto/request/MainCategoryRequestDto.java
  backend/src/main/java/com/funding/backend/domain/mainCategory/dto/response/MainCategoryResponseDto.java
  backend/src/main/java/com/funding/backend/domain/mainCategory/entity/MainCategory.java
  backend/src/main/java/com/funding/backend/domain/mainCategory/repository/MainCategoryRepository.java
  backend/src/main/java/com/funding/backend/domain/mainCategory/service/MainCategoryService.java
  backend/src/main/java/com/funding/backend/domain/project/dto/request/DonationCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/project/dto/request/ProjectCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/DonationProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/entity/Project.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/domain/projectSubCategory/controller/ProjectSubController.java
  backend/src/main/java/com/funding/backend/domain/projectSubCategory/dto/request/ProjectSubRequestDto.java
  backend/src/main/java/com/funding/backend/domain/projectSubCategory/dto/response/ProjectSubResponseDto.java
  backend/src/main/java/com/funding/backend/domain/projectSubCategory/entity/ProjectSubCategory.java
  backend/src/main/java/com/funding/backend/domain/projectSubCategory/repository/ProjectSubRepository.java
  backend/src/main/java/com/funding/backend/domain/projectSubCategory/service/ProjectSubCategoryService.java
  backend/src/main/java/com/funding/backend/domain/purchase/entity/Purchase.java
  backend/src/main/java/com/funding/backend/domain/subjectCategory/controller/SubjectCategoryController.java
  backend/src/main/java/com/funding/backend/domain/subjectCategory/dto/request/SubjectCategoryRequestDto.java
  backend/src/main/java/com/funding/backend/domain/subjectCategory/dto/response/SubjectCategoryResponseDto.java
  backend/src/main/java/com/funding/backend/domain/subjectCategory/entity/SubjectCategory.java
  backend/src/main/java/com/funding/backend/domain/subjectCategory/repository/SubjectCategoryRepository.java
  backend/src/main/java/com/funding/backend/domain/subjectCategory/service/SubjectCategoryService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: feat

#88 [ Refactor ] 78 : 프로젝트 승인 기능 구현 (명칭 수정)
  backend/src/main/java/com/funding/backend/domain/admin/controller/AdminController.java
  backend/src/main/java/com/funding/backend/domain/admin/service/AdminService.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationProjectService.java
  backend/src/main/java/com/funding/backend/domain/like/controller/LikeController.java
  backend/src/main/java/com/funding/backend/domain/like/service/LikeService.java
  backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/AuditProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/ProjectInfoResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/enums/ProjectStatus.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: refactor

#107 [ fix ] 75 : 인기 프로젝트 조회 쿼리 오류 수정
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
Labels: fix

#108 [ feat ] 41 : 후기 기능 구현
  backend/src/main/java/com/funding/backend/domain/purchase/repository/PurchaseRepository.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/domain/review/controller/ReviewController.java
  backend/src/main/java/com/funding/backend/domain/review/dto/request/ReviewRequestDto.java
  backend/src/main/java/com/funding/backend/domain/review/dto/response/ReviewResponseDto.java
  backend/src/main/java/com/funding/backend/domain/review/entity/Review.java
  backend/src/main/java/com/funding/backend/domain/review/repository/ReviewRepository.java
  backend/src/main/java/com/funding/backend/domain/review/service/ReviewService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#114 [ Feat ] 78 : 프로젝트 일괄 승인 기능 구현
  backend/src/main/java/com/funding/backend/domain/admin/controller/AdminController.java
  backend/src/main/java/com/funding/backend/domain/admin/service/AdminService.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/AuditProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
Labels: feat

#135 [ merge ] : dev 코드 main에 병합
  backend/src/main/java/com/funding/backend/domain/order/controller/PurchaseOrderController.java
  backend/src/main/java/com/funding/backend/domain/order/dto/response/PurchaseFileResponseDto.java
  backend/src/main/java/com/funding/backend/domain/order/service/PurchaseOrderService.java
  backend/src/main/java/com/funding/backend/domain/orderOption/service/OrderOptionService.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/global/config/PermitUrl.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#140 [ feat ] 139 : cors 설정 추가
  backend/src/main/java/com/funding/backend/global/config/PermitUrl.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
Labels: feat

#150 [ merge ] : 구매 프로젝트 응답 형식에 유저 정보 추가
  backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/PurchaseProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/funding/backend/domain/user/service/UserService.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
Labels: merge

#152 [ refact ] 151 : 토큰 유효시간 연장 3시간
  backend/src/main/java/com/funding/backend/security/jwt/JwtTokenizer.java
Labels: refactor

#163 [ Deploy ] 155 : https 환경 구성
  .github/workflows/deploy.yml
  .gitignore
  backend/src/main/java/com/funding/backend/global/config/SwaggerConfig.java
  docker-compose.override.yml
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
  nginx/nginx.local.conf
Labels: deploy

#171 [ feat ] 164 팔로우 목록 필드 추가
  backend/src/main/java/com/funding/backend/domain/follow/dto/response/FollowResponseDto.java
  backend/src/main/java/com/funding/backend/domain/follow/repository/FollowRepository.java
Labels: feat

#160 [ refact ] 157 : qna, review permitUrl 추가
  backend/src/main/java/com/funding/backend/global/config/PermitUrl.java
Labels: refactor

#179 [refact] 165 : 프로젝트 검색 응답dto변경
  backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/ProjectSearchResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
Labels: refactor

#194 [ fix ] : 86 리다이렉트 url 수정
  backend/src/main/java/com/funding/backend/global/config/PermitUrl.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
  backend/src/main/java/com/funding/backend/security/controller/AuthController.java
  backend/src/main/java/com/funding/backend/security/controller/TokenController.java
  backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/funding/backend/security/oauth/provider/GithubOAuthUserParser.java
  backend/src/main/java/com/funding/backend/security/oauth/provider/KakaoOAuthUserParser.java
Labels: fix

#254 [ feat ] 252 : 내가 생성한 구매형 프로젝트 리스트 조회
  backend/src/main/java/com/funding/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/funding/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/funding/backend/domain/project/entity/Project.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/funding/backend/domain/purchase/dto/response/PurchaseListResponseDto.java
  backend/src/main/java/com/funding/backend/domain/purchase/repository/PurchaseRepository.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
Labels: feat

#260 [ feat ] 256 : 구매 프로젝트 카테고리 별 조회 구현 완료
  backend/src/main/java/com/funding/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/funding/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/domain/purchase/controller/PurchaseController.java
  backend/src/main/java/com/funding/backend/domain/purchase/dto/response/PurchaseInfoResponseDto.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/domain/purchaseCategory/controller/CategoryController.java
  backend/src/main/java/com/funding/backend/domain/purchaseCategory/entity/PurchaseCategory.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
Labels: feat

#259 [ fix ] 237 쿠키에 액세스,리프레시 토큰
  backend/src/main/java/com/funding/backend/security/oauth/handler/OAuth2LoginSuccessHandler.java
Labels: fix

#262 [ feat ] 250 : 후원 프로젝트 생성 시 마일스톤(로드맵) 기능 구현
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationMilestoneRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationProjectDetail.java
  backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java
  backend/src/main/java/com/funding/backend/domain/donation/repository/DonationRepository.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationProjectService.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/controller/DonationMilestoneController.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneCreateDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneUpdateDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/entity/DonationMilestone.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/repository/DonationMilestoneRepository.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/service/DonationMilestoneService.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/DonationProjectResponseDto.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#264 [ feat ] : 258 사용자 상태 관리
  backend/src/main/java/com/funding/backend/domain/admin/controller/AdminController.java
  backend/src/main/java/com/funding/backend/domain/admin/service/AdminService.java
  backend/src/main/java/com/funding/backend/domain/user/entity/User.java
  backend/src/main/java/com/funding/backend/domain/user/service/UserService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#246 [ feat ] 84 : 알림 기능 구현
  backend/src/main/java/com/funding/backend/domain/alarm/controller/AlarmController.java
  backend/src/main/java/com/funding/backend/domain/alarm/dto/request/AlarmDto.java
  backend/src/main/java/com/funding/backend/domain/alarm/dto/request/AlarmRequestDto.java
  backend/src/main/java/com/funding/backend/domain/alarm/entity/Alarm.java
  backend/src/main/java/com/funding/backend/domain/alarm/enums/AlarmType.java
  backend/src/main/java/com/funding/backend/domain/alarm/event/NewPurchaseProjectRequest.java
  backend/src/main/java/com/funding/backend/domain/alarm/event/context/NewPurchaseProjectContext.java
  backend/src/main/java/com/funding/backend/domain/alarm/event/listener/AlarmEventListener.java
  backend/src/main/java/com/funding/backend/domain/alarm/policy/NotificationPolicy.java
  backend/src/main/java/com/funding/backend/domain/alarm/repository/AlarmRepository.java
  backend/src/main/java/com/funding/backend/domain/alarm/repository/EmitterRepository.java
  backend/src/main/java/com/funding/backend/domain/alarm/service/AlarmService.java
  backend/src/main/java/com/funding/backend/domain/alarm/service/alert/NewPurchaseProjectService.java
  backend/src/main/java/com/funding/backend/domain/alarm/strategy/AlarmStrategy.java
  backend/src/main/java/com/funding/backend/domain/alarm/strategy/factory/AlarmStrategyFactory.java
  backend/src/main/java/com/funding/backend/domain/alarm/strategy/strategy/NewPurchaseProjectStrategy.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/funding/backend/domain/user/service/UserService.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#273 [ merge ] : dev 코드 main에 병합
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
Labels: fix

#292 [ feat ] 251 : 후원 프로젝트 메인 카테고리별 조회 기능
  backend/src/main/java/com/funding/backend/domain/donation/controller/DonationController.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/response/DonationInfoResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
Labels: enhancement, feat

#293 [ merge ] dev 코드 main에 병합
  backend/src/main/java/com/funding/backend/domain/donation/controller/DonationController.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/response/DonationInfoResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
Labels: merge

#309 [ feat ] 308 : 내가 생성한 프로젝트 목록 조회 Dto 수정
  backend/src/main/java/com/funding/backend/domain/donation/dto/response/DonationListResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donation/repository/DonationRepository.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/purchase/dto/response/PurchaseListResponseDto.java
Labels: feat, refactor

#317 [ feat ] 304 : 사용자의 모든 알림 조회 기능
  backend/src/main/java/com/funding/backend/domain/alarm/controller/AlarmController.java
  backend/src/main/java/com/funding/backend/domain/alarm/dto/request/AlarmRequestDto.java
  backend/src/main/java/com/funding/backend/domain/alarm/dto/response/AlarmDto.java
  backend/src/main/java/com/funding/backend/domain/alarm/dto/response/AlarmListResponseDto.java
  backend/src/main/java/com/funding/backend/domain/alarm/dto/response/AlarmResponseDto.java
  backend/src/main/java/com/funding/backend/domain/alarm/repository/AlarmRepository.java
  backend/src/main/java/com/funding/backend/domain/alarm/service/AlarmService.java
  backend/src/main/java/com/funding/backend/domain/alarm/service/alert/NewPurchaseProjectService.java
  backend/src/main/java/com/funding/backend/domain/alarm/service/alert/NewPurchaseReceivedService.java
  backend/src/main/java/com/funding/backend/domain/alarm/service/alert/NewSuccessPurchaseService.java
  backend/src/main/java/com/funding/backend/domain/donation/controller/DonationController.java
Labels: feat

#325 [ feat ] 324 : 단일 알림 전체 알림 삭제 기능
  backend/src/main/java/com/funding/backend/domain/alarm/controller/AlarmController.java
  backend/src/main/java/com/funding/backend/domain/alarm/repository/AlarmRepository.java
  backend/src/main/java/com/funding/backend/domain/alarm/service/AlarmService.java
Labels: feat

#327 [ feat ] 313 : 후원 프로젝트 생성Dto와 수정Dto 형식 통일
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationMilestoneRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationProjectDetail.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationRewardRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java
  backend/src/main/java/com/funding/backend/domain/donation/repository/DonationRepository.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationProjectService.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/controller/DonationMilestoneController.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneCreateDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneUpdateDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/entity/DonationMilestone.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/repository/DonationMilestoneRepository.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/service/DonationMilestoneService.java
  backend/src/main/java/com/funding/backend/domain/donationReward/controller/DonationRewardController.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/request/DonationRewardCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/request/DonationRewardUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/response/DonationRewardDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/response/DonationRewardResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/entity/DonationReward.java
  backend/src/main/java/com/funding/backend/domain/donationReward/repository/DonationRewardRepository.java
  backend/src/main/java/com/funding/backend/domain/donationReward/service/DonationRewardService.java
  backend/src/main/java/com/funding/backend/domain/orderReward/dto/response/OrderRewardResponseDto.java
  backend/src/main/java/com/funding/backend/domain/orderReward/entity/OrderReward.java
  backend/src/main/java/com/funding/backend/domain/orderReward/repository/OrderRewardRepository.java
  backend/src/main/java/com/funding/backend/domain/orderReward/service/OrderRewardService.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/DonationProjectResponseDto.java
Labels: feat

#329 [ merge ] dev 코드 main에 병합
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationMilestoneRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationProjectDetail.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationRewardRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/request/DonationUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donation/entity/Donation.java
  backend/src/main/java/com/funding/backend/domain/donation/repository/DonationRepository.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationProjectService.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/controller/DonationMilestoneController.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneCreateDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/request/DonationMilestoneUpdateDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/dto/response/DonationMilestoneResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/entity/DonationMilestone.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/repository/DonationMilestoneRepository.java
  backend/src/main/java/com/funding/backend/domain/donationMilestone/service/DonationMilestoneService.java
  backend/src/main/java/com/funding/backend/domain/donationReward/controller/DonationRewardController.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/request/DonationRewardCreateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/request/DonationRewardUpdateRequestDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/response/DonationRewardDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/dto/response/DonationRewardResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donationReward/entity/DonationReward.java
  backend/src/main/java/com/funding/backend/domain/donationReward/repository/DonationRewardRepository.java
  backend/src/main/java/com/funding/backend/domain/donationReward/service/DonationRewardService.java
  backend/src/main/java/com/funding/backend/domain/orderReward/dto/response/OrderRewardResponseDto.java
  backend/src/main/java/com/funding/backend/domain/orderReward/entity/OrderReward.java
  backend/src/main/java/com/funding/backend/domain/orderReward/repository/OrderRewardRepository.java
  backend/src/main/java/com/funding/backend/domain/orderReward/service/OrderRewardService.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/DonationProjectResponseDto.java
Labels: merge

#328 [ feat ] 219 : 신고 기능 구현
  backend/src/main/java/com/funding/backend/BackendApplication.java
  backend/src/main/java/com/funding/backend/domain/report/controller/ReportController.java
  backend/src/main/java/com/funding/backend/domain/report/dto/request/ReportRequestDto.java
  backend/src/main/java/com/funding/backend/domain/report/dto/response/ReportResponseDto.java
  backend/src/main/java/com/funding/backend/domain/report/entity/Report.java
  backend/src/main/java/com/funding/backend/domain/report/repository/ReportRepository.java
  backend/src/main/java/com/funding/backend/domain/report/service/ReportService.java
  backend/src/main/java/com/funding/backend/enums/ReportCategory.java
  backend/src/main/java/com/funding/backend/enums/ReportStatus.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#334 [ merge ] dev 코드 main에 병합
  backend/src/main/java/com/funding/backend/domain/alarm/controller/AlarmController.java
  backend/src/main/java/com/funding/backend/domain/donation/controller/DonationController.java
  backend/src/main/java/com/funding/backend/domain/donation/dto/response/DonationInfoResponseDto.java
  backend/src/main/java/com/funding/backend/domain/donation/service/DonationService.java
  backend/src/main/java/com/funding/backend/domain/order/entity/Order.java
  backend/src/main/java/com/funding/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/funding/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/funding/backend/domain/project/controller/ProjectController.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/DonationProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/ProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/PurchaseProjectResponseDto.java
  backend/src/main/java/com/funding/backend/domain/project/entity/Project.java
  backend/src/main/java/com/funding/backend/domain/project/repository/ProjectRepository.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectViewCountService.java
  backend/src/main/java/com/funding/backend/domain/purchase/service/PurchaseService.java
  backend/src/main/java/com/funding/backend/domain/settlement/factory/SettlementFactory.java
  backend/src/main/java/com/funding/backend/domain/settlement/factory/SettlementPeriod.java
  backend/src/main/java/com/funding/backend/domain/settlement/factory/SettlementPeriodFactory.java
  backend/src/main/java/com/funding/backend/domain/settlement/factory/SettlementProperties.java
  backend/src/main/java/com/funding/backend/domain/settlement/repository/SettlementRepository.java
  backend/src/main/java/com/funding/backend/domain/settlement/schedule/SettlementScheduler.java
  backend/src/main/java/com/funding/backend/domain/settlement/service/SettlementService.java
  backend/src/main/java/com/funding/backend/global/config/YetdaSecurityConfig.java
  backend/src/main/java/com/funding/backend/global/toss/controller/TossController.java
  backend/src/main/java/com/funding/backend/global/toss/service/TossService.java
  backend/src/main/resources/application.yml
Labels: merge

#339 [ Feat ] 223 : 후원 주문 기능과 정산 기능 추가
  backend/src/main/java/com/funding/backend/domain/order/controller/DonationOrderController.java
  backend/src/main/java/com/funding/backend/domain/order/dto/request/DonationOrderRequestDto.java
  backend/src/main/java/com/funding/backend/domain/order/dto/response/DonationOrderResponseDto.java
  backend/src/main/java/com/funding/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/funding/backend/domain/order/service/DonationOrderService.java
  backend/src/main/java/com/funding/backend/domain/project/dto/response/ProjectInfoResponseDto.java
  backend/src/main/java/com/funding/backend/domain/settlement/schedule/SettlementScheduler.java
  backend/src/main/java/com/funding/backend/domain/settlement/service/SettlementService.java
  backend/src/main/java/com/funding/backend/global/exception/ExceptionCode.java
Labels: feat

#345 [ dev ] : dev 코드 main에 병합
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectViewCountService.java
  backend/src/main/java/com/funding/backend/domain/settlement/controller/AdminSettlementController.java
  backend/src/main/java/com/funding/backend/domain/settlement/controller/SettlementController.java
  backend/src/main/java/com/funding/backend/domain/settlement/dto/response/SettlementMonthlyTotalAdminResponseDto.java
  backend/src/main/java/com/funding/backend/domain/settlement/dto/response/SettlementProjectSummaryAdminResponseDto.java
  backend/src/main/java/com/funding/backend/domain/settlement/service/SettlementService.java
Labels: feat

#348 [ merge ] : dev 코드 main 에 push
  backend/src/main/java/com/funding/backend/domain/order/entity/Order.java
  backend/src/main/java/com/funding/backend/domain/order/repository/OrderRepository.java
  backend/src/main/java/com/funding/backend/domain/order/service/OrderService.java
  backend/src/main/java/com/funding/backend/domain/project/service/ProjectService.java
  backend/src/main/java/com/funding/backend/domain/settlement/controller/AdminSettlementController.java
  backend/src/main/java/com/funding/backend/domain/settlement/service/SettlementService.java
Labels: merge
